### 
GET http://localhost:8080/


###
GET http://localhost:8080/all-movies


### 
POST http://localhost:8080/add-movie
Content-Type: application/json

{
  "id": "12",
  "titulo": "Fight Club",
  "genero": "Drama",
  "duracao": 139,
  "classificacao_etaria": "18"
}


### 
PUT http://localhost:8080/update-movie/1
Content-Type: application/json

{
  "titulo": "The Matrix Reloaded",
  "genero": "Sci-Fi",
  "duracao": 138,
  "classificacao_etaria": "14"
}


### 
DELETE http://localhost:8080/delete-movie/1